version: 2.1
jobs:
  lint:
    resource_class: small
    docker:
      - image: circleci/golang:1.11.13
    parallelism: 1
    steps:
      - checkout
      - run:
          name: make effxhq directory
          command: mkdir -p /go/src/github.com/effxhq
      - run:
          name: clone backeffx
          command: git -C /go/src/github.com/effxhq clone git@github.com:effxhq/backeffx.git
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Go mod download
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: lint
          command: go run github.com/golangci/golangci-lint/cmd/golangci-lint run -c ./.golangci.yml -E gochecknoinits -E gocyclo -E gosec -E interfacer -E maligned -E misspell -E nakedret -E unconvert -E unparam
workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
