name: effx lint
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint effx configuration files
        uses: effxhq/effx-lint-action@master
        with:
          directory: /github/workspace
        env:
          EFFX_API_KEY: ${{ secrets.EFFX_API_KEY }}
